config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :doctors
      resources :patients

      root to: "users#index"
    end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: redirect('/patients')
  resources :patients
  resources :doctors
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doctor.rb
# frozen_string_literal: true

class Doctor < ApplicationRecord
  validates :first_name, :last_name, :practicing_from, :qualification_number, :employment, presence: true
  validates :qualification_number, uniqueness: true

  has_many :patients

  enum employment: {
    'Full time': 0,
    'Part time': 1,
    'Intern': 2,
    'Contract': 3
  }
  end

app/models/patient.rb
# frozen_string_literal: true

class Patient < ApplicationRecord
  validates :first_name, :last_name, :age, :gender, presence: true

  belongs_to :doctor, optional: true

  enum gender: {
    male: 0,
    female: 1,
    other: 2
  }
  end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/doctors_controller.rb
module Admin
  class DoctorsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/patients_controller.rb
module Admin
  class PatientsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name avatar])
  end
end

app/controllers/doctors_controller.rb
# frozen_string_literal: true

class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:edit, :update, :show, :destroy]

  def index
    @doctors = Doctor.all.order('id ASC')
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save
      redirect_to doctors_path
    else
      flash[:error] = @doctor.errors&.messages
      render 'new'
    end
  end


  def show
  end

  def edit 
  end

  def update
    @doctor = Doctor.find(params[:id])

    if @doctor.update(doctor_params)
      flash[:notice] = "Doctor was successfully updated"
      redirect_to doctors_path
    else
      flash[:error] = "Doctor can not be updated"
      render 'edit'
    end
  end

  def destroy
    message = @doctor.destroy ? {notice: "Doctor was successfully deleted"} : {error: "Doctor couldn't be deleted"}
    if @doctor.destroy
      redirect_to doctors_path, message
    end
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :practicing_from, :qualification_number, :employment)
  end
end

app/controllers/patients_controller.rb
# frozen_string_literal: true

class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  def index
    @patients = Patient.all.includes(:doctor).order('id ASC')
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      flash[:notice] = "Patient was successfully created"
      redirect_to patients_path
    else
      flash[:error] = "Patient can not be created"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update

    if @patient.update(patient_params)
      flash[:notice] = "Patient was successfully updated"
      redirect_to patients_path
    else
      flash[:error] = "Patient can not be updated"
      render 'edit'
    end
  end

  def destroy
    message = @patient.destroy ? {notice: "Patient was successfully deleted"} : {error: "Patient couldn't be deleted"}
    if @patient.destroy
      redirect_to patients_path, message
    end
  end

  private
  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:first_name, :last_name, :age, :gender, :doctor_id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/doctors/_doctor.html.erb
<tr>
  <td><%= link_to doctor.first_name, doctor_path(doctor) %></td>
  <td><%= doctor.last_name %></td>
  <td><%= doctor.practicing_from %></td>
  <td><%= doctor.qualification_number %></td>
  <td><%= doctor.employment %></td>
  <td><%= link_to 'Edit', edit_doctor_path(doctor), class: 'btn btn-warning' %></td>
  <td><%= link_to 'Delete', [doctor], method: :delete, class: 'btn btn-danger' %></td>
</tr>

app/views/doctors/edit.html.erb
<h1>Update Doctor</h1>

<%= form_for @doctor do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <%= f.label :practicing_from %>
    <%= f.date_field :practicing_from %>
    <%= f.label :qualification_number %>
    <%= f.number_field :qualification_number %>
    <%= f.label :employment %>
    <%= f.select :employment, Doctor.employments.keys %>
    <%= f.submit 'Save' %>
<% end %>

app/views/doctors/index.html.erb
<p></p>
<div class="listing">
  <h2>List of Doctors</h2>
  <div>
  <%= link_to "New Doctor", new_doctor_path, method: :get, class: 'btn btn-primary' %>
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Practicing from</th>
      <th>Qualification number</th>
      <th>Employment</th>
      <th>Actions</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= render @doctors %>
  </tbody>
</table>

app/views/doctors/new.html.erb
<h1>Create Doctors</h1>

<%= form_for @doctor do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <%= f.label :practicing_from %>
    <%= f.date_field :practicing_from %>
    <%= f.label :qualification_number %>
    <%= f.number_field :qualification_number %>
    <%= f.label :employment %>
    <%= f.select :employment, Doctor.employments.keys %>
    <%= f.submit 'Submit' %>
<% end %>

app/views/doctors/show.html.erb
<%= link_to '< Go back', doctors_path, class: 'btn btn-primary' %>
<p></p>
<%= @doctor.first_name %>
<%= @doctor.last_name %>
<p><%= @doctor.practicing_from %></p>
<p><%= @doctor.qualification_number %></p>
<p><%= @doctor.employment %></p>

<%= link_to 'Edit', edit_doctor_path(@doctor), class: 'btn btn-warning' %>
<%= link_to 'Delete', [@doctor], method: :delete, class: 'btn btn-warning' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsHtdAcademyBackend</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-dark bg-dark">
  <% if current_user %>
  <div class="container">
 
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to "Home", patients_path, class: 'navbar-brand' %>
      </li>
      <li class="nav-item">
      <%= link_to "Patients", patients_path, class: 'nav-link' %>
      
      </li>
      <li class="nav-item">
      <%= link_to "Doctors", doctors_path, class: 'nav-link' %>
      </li>
      <% if current_user.avatar.attached? %>
      <li>
      <%= image_tag current_user.avatar, size: 40, class: 'rounded-circle' %>
      </li>
      <% end %>
      
      <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link' %>
      </li>
      
    </ul>
    
  </div>
  </div>
  <% end %>
  </nav>


  <div class="container mt-5">
  <div class="text-right">
    
   
    <span><%#= current_user.email %></span>
    
    

    </div>
    <p></p>
    <% if flash[:notice] %>
    <div class="alert alert-info">
      <%= flash[:notice] %>
    </div>
    <% end %>
    <% if flash[:error] %>
    <div class="alert alert-danger">
      <%= flash[:error] %>
    </div>
    <% end %>
    <p></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for patient do |f| %>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
    <%= f.label :age %>
    <%= f.number_field :age %>
    <%= f.label :gender %>
    <%= f.select :gender, Patient.genders.keys %>
    <%= f.label :doctor_id %>
    <%= f.select :doctor_id, Doctor.all.map { |doctor| ["#{doctor.first_name} #{doctor.last_name}", doctor.id] } %>
    <%= f.submit 'Save' %>

<% end %>

app/views/patients/edit.html.erb
<h1>Update Patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/index.html.erb
<div class="listing">
  <h2>List of Patients</h2>
  <div>
  <%= link_to "New Patient", new_patient_path, method: :get, class: 'btn btn-primary' %>
  </div>
</div>
<table class="table">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Gender</th>
      <th>Doctor</th>
      <th>Actions</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  
  <tbody>
  <% @patients.each do |patient| %>
    <tr>
      <td><%= link_to patient.first_name, patient_path(patient) %></td>
      <td><%= patient.last_name %></td>
      <td><%= patient.age %></td>
      <td><%= patient.gender.titleize %></td>
      <td><%= patient.doctor&.first_name %></td>
      <td><%= link_to 'Edit', edit_patient_path(patient), class: 'btn btn-warning' %></td>
      <td><%= link_to 'Delete', [patient], method: :delete, class: 'btn btn-danger' %><td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/patients/new.html.erb
<h1>Create Patients</h1>

<%= render 'form', patient: @patient %>

app/views/patients/show.html.erb
<%= link_to '< Go back', patients_path, class: 'btn btn-primary' %>
<p></p>
<%= @patient.first_name %>
<%= @patient.last_name %>
<p><%= @patient.age %></p>
<%= @patient.doctor.first_name %>
<%= @patient.doctor.last_name %>
<p></p>
<%= link_to 'Edit', edit_patient_path(@patient), class: 'btn btn-warning' %>
<%= link_to 'Delete', [@patient], method: :delete, class: 'btn btn-warning' %>